language: java

jobs:
  include:
    - stage: Test
      script: mvn test -Dtest=!ppd.PPDTest
      after_success:
       - mvn clean test jacoco:report coveralls:report
    - stage: Test
      script: mvn test -Dtest=ppd.PPDTest
