name: Run Tests
on:
  push:
    branches:
      - "**/*"
  pull_request:
    branches:
      - "**/*"
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: zulu
          java-version: "8"
      - name: 📦 Build with Maven
        run: mvn --batch-mode --update-snapshots test -Dtest=!ppd.PPDTest jacoco:report
      # Disable Coveralls for now
      # - name: 🚀 Coveralls Coverage Report Submission
      #   run: mvn coveralls:report
  PPD:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: zulu
          java-version: "8"
      - run: mvn test -Dtest=ppd.PPDTest
